name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH dependencies
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH Agent
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          echo "" >> ~/.ssh/id_rsa  # Ensures a trailing newline
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ~/babd
            git pull origin main
            npm install
            npm run build
            pm2 restart babd-app
          "
